name: 'Local directory cache'
description: 'Cache to a local directory'
author: 'Odyssey'
inputs:
  path:
    required: true
    description: 'Directory to cache, relative to working directory.'
  key:
    required: true
    description: 'Key to use to store the cache.'
  restore-keys:
    required: true
    description: 'Ordered list of keys to try to find existing cache entry.'
  cache-dir:
    required: true
    description: 'Local cache directory.'
runs:
  using: 'node12'
  main: 'dist/action_restore/index.js'
  post: 'dist/action_save/index.js'
  post-if: 'success()'
