name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
      - run: |
          npm run all
  test:  # sortof an integration test
    runs-on: ubuntu-latest
    if: contains(github.ref, "release")
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        env:
          cache-name: build
        with:
          path: Library
          key: foo-bar-baz
          restore-keys: |
            doesntexist
            foo-bar-
          cache-dir: ${{github.workspace}}/__tests__/cacheDir
