name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: |
          npm install
      - run: |
          npm run all
  test:  # sortof an integration test
    runs-on: ubuntu-latest
    if: contains(github.ref, 'release')
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        env:
          cache-name: build
        with:
          path: Library
          key: foo-bar-baz
          restore-keys: |
            doesntexist
            foo-bar-
          cache-dir: ${{github.workspace}}/__tests__/cacheDir
